name: Test and Deploy

on:
 
  push:
    branches: [ master ]

jobs:
  
  build:
    
    name: Test and Deploy
    runs-on: ubuntu-latest
    environment: cicd
    
    steps:
    
    - name: Check out code
      uses: actions/checkout@v3
    
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v3
      with: 
        dotnet-version: '6.0.x'
    
    - name: Run Unit Tests
      run: dotnet test
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: demoforum
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG Server/.
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
